name: Package
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
    types: [closed]

jobs:
  package:
    name: Package and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install bumpversion dependency
        run: |
          python -m pip install --upgrade pip
          pip install bump2version pyyaml
      - name: Bump version if necessary for cloudlaunchserver
        run: sh -c 'sh ./.github/scripts/bump.sh'
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_BRANCH: ${{ github.event.pull_request.base.ref }}
          CHART_NAME: cloudlaunchserver
      - name: Package and push to helm-charts for cloudlaunchserver
        run: sh ./.github/scripts/package.sh
        shell: bash
        env:
          CHARTS_REPO: cloudve/helm-charts
          GIT_TOKEN: ${{ secrets.CHARTS_TOKEN }}
          CHART_NAME: cloudlaunchserver
          CHARTS_BRANCH: ${{ github.event.pull_request.base.ref }}
      - name: Bump version if necessary for cloudlaunch
        run: sh -c 'sh ./.github/scripts/bump.sh'
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_BRANCH: ${{ github.event.pull_request.base.ref }}
          CHART_NAME: cloudlaunch
      - name: Package and push to helm-charts for cloudlaunch
        run: sh ./.github/scripts/package.sh
        shell: bash
        env:
          CHARTS_REPO: almahmoud/helm-charts
          GIT_TOKEN: ${{ secrets.CHARTS_TOKEN }}
          CHART_NAME: cloudlaunch
          CHARTS_BRANCH: ${{ github.event.pull_request.base.ref }}
